-- Create a table for public profiles referencing auth.users
create table public.users (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.users enable row level security;

-- Create policies for public.users
create policy "Public profiles are viewable by everyone."
  on public.users for select
  using ( true );

create policy "Users can insert their own profile."
  on public.users for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.users for update
  using ( auth.uid() = id );

-- Create water_logs table
create table public.water_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) not null,
  amount_ml integer not null,
  logged_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for water_logs
alter table public.water_logs enable row level security;

create policy "Users can view own water logs."
  on public.water_logs for select
  using ( auth.uid() = user_id );

create policy "Users can insert own water logs."
  on public.water_logs for insert
  with check ( auth.uid() = user_id );

create policy "Users can update own water logs."
  on public.water_logs for update
  using ( auth.uid() = user_id );

create policy "Users can delete own water logs."
  on public.water_logs for delete
  using ( auth.uid() = user_id );

-- Create reports table
create table public.reports (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) not null,
  content text,
  period_type text check (period_type in ('DAILY', 'WEEKLY')),
  start_date date,
  end_date date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for reports
alter table public.reports enable row level security;

create policy "Users can view own reports."
  on public.reports for select
  using ( auth.uid() = user_id );

-- Function to handle new user creation (optional but recommended)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, email, full_name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to automatically create public profile on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
